/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/about.vue')['default']
    AgentChat: typeof import('./src/components/agent-chat.vue')['default']
    AgentChat_bk: typeof import('./src/components/agent-chat_bk.vue')['default']
    AiStockPick: typeof import('./src/components/ai-stock-pick.vue')['default']
    AnimatedCounter: typeof import('./src/components/AnimatedCounter.vue')['default']
    ClsCalendarTimeLine: typeof import('./src/components/ClsCalendarTimeLine.vue')['default']
    EmbeddedUrl: typeof import('./src/components/EmbeddedUrl.vue')['default']
    Fund: typeof import('./src/components/fund.vue')['default']
    HotEvents: typeof import('./src/components/HotEvents.vue')['default']
    HotStockList: typeof import('./src/components/HotStockList.vue')['default']
    HotTopics: typeof import('./src/components/HotTopics.vue')['default']
    IndustryMoneyRank: typeof import('./src/components/industryMoneyRank.vue')['default']
    IndustryResearchReportList: typeof import('./src/components/IndustryResearchReportList.vue')['default']
    InvestCalendarTimeLine: typeof import('./src/components/InvestCalendarTimeLine.vue')['default']
    KLineChart: typeof import('./src/components/KLineChart.vue')['default']
    KLineChartWithSignals: typeof import('./src/components/KLineChartWithSignals.vue')['default']
    LongTigerRankList: typeof import('./src/components/LongTigerRankList.vue')['default']
    Market: typeof import('./src/components/market.vue')['default']
    McpSettings: typeof import('./src/components/mcp-settings.vue')['default']
    MoneyTrend: typeof import('./src/components/moneyTrend.vue')['default']
    MultiStockComparison: typeof import('./src/components/MultiStockComparison.vue')['default']
    NewsList: typeof import('./src/components/newsList.vue')['default']
    PositionAllocationPie: typeof import('./src/components/PositionAllocationPie.vue')['default']
    PositionAnalysis: typeof import('./src/components/position-analysis.vue')['default']
    RankTable: typeof import('./src/components/rankTable.vue')['default']
    RecommendationWordCloud: typeof import('./src/components/RecommendationWordCloud.vue')['default']
    ReportViewer: typeof import('./src/components/ReportViewer.vue')['default']
    RiskReturnScatter: typeof import('./src/components/RiskReturnScatter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectStock: typeof import('./src/components/SelectStock.vue')['default']
    Settings: typeof import('./src/components/settings.vue')['default']
    Stock: typeof import('./src/components/stock.vue')['default']
    Stockhotmap: typeof import('./src/components/stockhotmap.vue')['default']
    StockNoticeList: typeof import('./src/components/StockNoticeList.vue')['default']
    StockRadarChart: typeof import('./src/components/StockRadarChart.vue')['default']
    StockResearchReportList: typeof import('./src/components/StockResearchReportList.vue')['default']
    StockSparkLine: typeof import('./src/components/stockSparkLine.vue')['default']
    TChat: typeof import('@tdesign-vue-next/chat')['Chat']
    TChatAction: typeof import('@tdesign-vue-next/chat')['ChatAction']
    TChatContent: typeof import('@tdesign-vue-next/chat')['ChatContent']
    TChatLoading: typeof import('@tdesign-vue-next/chat')['ChatLoading']
    TChatSender: typeof import('@tdesign-vue-next/chat')['ChatSender']
    TechIndicatorCard: typeof import('./src/components/TechIndicatorCard.vue')['default']
    ToolSettings: typeof import('./src/components/tool-settings.vue')['default']
  }
}
