// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Follow(arg1) {
  return window['go']['main']['App']['Follow'](arg1);
}

export function GetFollowList() {
  return window['go']['main']['App']['GetFollowList']();
}

export function GetStockList(arg1) {
  return window['go']['main']['App']['GetStockList'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SetCostPriceAndVolume(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCostPriceAndVolume'](arg1, arg2, arg3);
}

export function UnFollow(arg1) {
  return window['go']['main']['App']['UnFollow'](arg1);
}
