// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';

export function Follow(arg1:string):Promise<string>;

export function GetFollowList():Promise<Array<data.FollowedStock>>;

export function GetStockList(arg1:string):Promise<Array<data.StockBasic>>;

export function Greet(arg1:string):Promise<data.StockInfo>;

export function UnFollow(arg1:string):Promise<string>;
