// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {data} from '../models';

export function Follow(arg1:string):Promise<string>;

export function GetAIResponseResult(arg1:string):Promise<models.AIResponseResult>;

export function GetConfig():Promise<data.Settings>;

export function GetFollowList():Promise<Array<data.FollowedStock>>;

export function GetStockList(arg1:string):Promise<Array<data.StockBasic>>;

export function GetVersionInfo():Promise<models.VersionInfo>;

export function Greet(arg1:string):Promise<data.StockInfo>;

export function NewChatStream(arg1:string,arg2:string):Promise<void>;

export function SaveAIResponseResult(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendDingDingMessage(arg1:string,arg2:string):Promise<string>;

export function SendDingDingMessageByType(arg1:string,arg2:string,arg3:number):Promise<string>;

export function SetAlarmChangePercent(arg1:number,arg2:number,arg3:string):Promise<string>;

export function SetCostPriceAndVolume(arg1:string,arg2:number,arg3:number):Promise<string>;

export function SetStockSort(arg1:number,arg2:string):Promise<void>;

export function UnFollow(arg1:string):Promise<string>;

export function UpdateConfig(arg1:data.Settings):Promise<string>;
